// Code generated by entc, DO NOT EDIT.

package emailtemplate

const (
	// Label holds the string label denoting the emailtemplate type in the database.
	Label = "email_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the emailtemplate in the database.
	Table = "email_templates"
)

// Columns holds all SQL columns for emailtemplate fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
