// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppEmailTemplatesColumns holds the columns for the "app_email_templates" table.
	AppEmailTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "lang_id", Type: field.TypeUUID},
		{Name: "sender", Type: field.TypeString},
		{Name: "reply_to", Type: field.TypeString},
		{Name: "cc_to", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
	}
	// AppEmailTemplatesTable holds the schema information for the "app_email_templates" table.
	AppEmailTemplatesTable = &schema.Table{
		Name:       "app_email_templates",
		Columns:    AppEmailTemplatesColumns,
		PrimaryKey: []*schema.Column{AppEmailTemplatesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppEmailTemplatesTable,
	}
)

func init() {
}
