// Code generated by entc, DO NOT EDIT.

package appemailtemplate

const (
	// Label holds the string label denoting the appemailtemplate type in the database.
	Label = "app_email_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the appemailtemplate in the database.
	Table = "app_email_templates"
)

// Columns holds all SQL columns for appemailtemplate fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
