// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appcontact"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppContactUpdate is the builder for updating AppContact entities.
type AppContactUpdate struct {
	config
	hooks    []Hook
	mutation *AppContactMutation
}

// Where appends a list predicates to the AppContactUpdate builder.
func (acu *AppContactUpdate) Where(ps ...predicate.AppContact) *AppContactUpdate {
	acu.mutation.Where(ps...)
	return acu
}

// SetAppID sets the "app_id" field.
func (acu *AppContactUpdate) SetAppID(u uuid.UUID) *AppContactUpdate {
	acu.mutation.SetAppID(u)
	return acu
}

// SetUsedFor sets the "used_for" field.
func (acu *AppContactUpdate) SetUsedFor(s string) *AppContactUpdate {
	acu.mutation.SetUsedFor(s)
	return acu
}

// SetSender sets the "sender" field.
func (acu *AppContactUpdate) SetSender(s string) *AppContactUpdate {
	acu.mutation.SetSender(s)
	return acu
}

// SetAccount sets the "account" field.
func (acu *AppContactUpdate) SetAccount(s string) *AppContactUpdate {
	acu.mutation.SetAccount(s)
	return acu
}

// SetAccountType sets the "account_type" field.
func (acu *AppContactUpdate) SetAccountType(s string) *AppContactUpdate {
	acu.mutation.SetAccountType(s)
	return acu
}

// SetCreateAt sets the "create_at" field.
func (acu *AppContactUpdate) SetCreateAt(u uint32) *AppContactUpdate {
	acu.mutation.ResetCreateAt()
	acu.mutation.SetCreateAt(u)
	return acu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (acu *AppContactUpdate) SetNillableCreateAt(u *uint32) *AppContactUpdate {
	if u != nil {
		acu.SetCreateAt(*u)
	}
	return acu
}

// AddCreateAt adds u to the "create_at" field.
func (acu *AppContactUpdate) AddCreateAt(u int32) *AppContactUpdate {
	acu.mutation.AddCreateAt(u)
	return acu
}

// SetUpdateAt sets the "update_at" field.
func (acu *AppContactUpdate) SetUpdateAt(u uint32) *AppContactUpdate {
	acu.mutation.ResetUpdateAt()
	acu.mutation.SetUpdateAt(u)
	return acu
}

// AddUpdateAt adds u to the "update_at" field.
func (acu *AppContactUpdate) AddUpdateAt(u int32) *AppContactUpdate {
	acu.mutation.AddUpdateAt(u)
	return acu
}

// Mutation returns the AppContactMutation object of the builder.
func (acu *AppContactUpdate) Mutation() *AppContactMutation {
	return acu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (acu *AppContactUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	acu.defaults()
	if len(acu.hooks) == 0 {
		if err = acu.check(); err != nil {
			return 0, err
		}
		affected, err = acu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppContactMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = acu.check(); err != nil {
				return 0, err
			}
			acu.mutation = mutation
			affected, err = acu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(acu.hooks) - 1; i >= 0; i-- {
			if acu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, acu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (acu *AppContactUpdate) SaveX(ctx context.Context) int {
	affected, err := acu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (acu *AppContactUpdate) Exec(ctx context.Context) error {
	_, err := acu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acu *AppContactUpdate) ExecX(ctx context.Context) {
	if err := acu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acu *AppContactUpdate) defaults() {
	if _, ok := acu.mutation.UpdateAt(); !ok {
		v := appcontact.UpdateDefaultUpdateAt()
		acu.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acu *AppContactUpdate) check() error {
	if v, ok := acu.mutation.UsedFor(); ok {
		if err := appcontact.UsedForValidator(v); err != nil {
			return &ValidationError{Name: "used_for", err: fmt.Errorf(`ent: validator failed for field "AppContact.used_for": %w`, err)}
		}
	}
	return nil
}

func (acu *AppContactUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appcontact.Table,
			Columns: appcontact.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appcontact.FieldID,
			},
		},
	}
	if ps := acu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appcontact.FieldAppID,
		})
	}
	if value, ok := acu.mutation.UsedFor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldUsedFor,
		})
	}
	if value, ok := acu.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldSender,
		})
	}
	if value, ok := acu.mutation.Account(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldAccount,
		})
	}
	if value, ok := acu.mutation.AccountType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldAccountType,
		})
	}
	if value, ok := acu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldCreateAt,
		})
	}
	if value, ok := acu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldCreateAt,
		})
	}
	if value, ok := acu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldUpdateAt,
		})
	}
	if value, ok := acu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, acu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appcontact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AppContactUpdateOne is the builder for updating a single AppContact entity.
type AppContactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppContactMutation
}

// SetAppID sets the "app_id" field.
func (acuo *AppContactUpdateOne) SetAppID(u uuid.UUID) *AppContactUpdateOne {
	acuo.mutation.SetAppID(u)
	return acuo
}

// SetUsedFor sets the "used_for" field.
func (acuo *AppContactUpdateOne) SetUsedFor(s string) *AppContactUpdateOne {
	acuo.mutation.SetUsedFor(s)
	return acuo
}

// SetSender sets the "sender" field.
func (acuo *AppContactUpdateOne) SetSender(s string) *AppContactUpdateOne {
	acuo.mutation.SetSender(s)
	return acuo
}

// SetAccount sets the "account" field.
func (acuo *AppContactUpdateOne) SetAccount(s string) *AppContactUpdateOne {
	acuo.mutation.SetAccount(s)
	return acuo
}

// SetAccountType sets the "account_type" field.
func (acuo *AppContactUpdateOne) SetAccountType(s string) *AppContactUpdateOne {
	acuo.mutation.SetAccountType(s)
	return acuo
}

// SetCreateAt sets the "create_at" field.
func (acuo *AppContactUpdateOne) SetCreateAt(u uint32) *AppContactUpdateOne {
	acuo.mutation.ResetCreateAt()
	acuo.mutation.SetCreateAt(u)
	return acuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (acuo *AppContactUpdateOne) SetNillableCreateAt(u *uint32) *AppContactUpdateOne {
	if u != nil {
		acuo.SetCreateAt(*u)
	}
	return acuo
}

// AddCreateAt adds u to the "create_at" field.
func (acuo *AppContactUpdateOne) AddCreateAt(u int32) *AppContactUpdateOne {
	acuo.mutation.AddCreateAt(u)
	return acuo
}

// SetUpdateAt sets the "update_at" field.
func (acuo *AppContactUpdateOne) SetUpdateAt(u uint32) *AppContactUpdateOne {
	acuo.mutation.ResetUpdateAt()
	acuo.mutation.SetUpdateAt(u)
	return acuo
}

// AddUpdateAt adds u to the "update_at" field.
func (acuo *AppContactUpdateOne) AddUpdateAt(u int32) *AppContactUpdateOne {
	acuo.mutation.AddUpdateAt(u)
	return acuo
}

// Mutation returns the AppContactMutation object of the builder.
func (acuo *AppContactUpdateOne) Mutation() *AppContactMutation {
	return acuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (acuo *AppContactUpdateOne) Select(field string, fields ...string) *AppContactUpdateOne {
	acuo.fields = append([]string{field}, fields...)
	return acuo
}

// Save executes the query and returns the updated AppContact entity.
func (acuo *AppContactUpdateOne) Save(ctx context.Context) (*AppContact, error) {
	var (
		err  error
		node *AppContact
	)
	acuo.defaults()
	if len(acuo.hooks) == 0 {
		if err = acuo.check(); err != nil {
			return nil, err
		}
		node, err = acuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppContactMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = acuo.check(); err != nil {
				return nil, err
			}
			acuo.mutation = mutation
			node, err = acuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(acuo.hooks) - 1; i >= 0; i-- {
			if acuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, acuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (acuo *AppContactUpdateOne) SaveX(ctx context.Context) *AppContact {
	node, err := acuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (acuo *AppContactUpdateOne) Exec(ctx context.Context) error {
	_, err := acuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acuo *AppContactUpdateOne) ExecX(ctx context.Context) {
	if err := acuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acuo *AppContactUpdateOne) defaults() {
	if _, ok := acuo.mutation.UpdateAt(); !ok {
		v := appcontact.UpdateDefaultUpdateAt()
		acuo.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acuo *AppContactUpdateOne) check() error {
	if v, ok := acuo.mutation.UsedFor(); ok {
		if err := appcontact.UsedForValidator(v); err != nil {
			return &ValidationError{Name: "used_for", err: fmt.Errorf(`ent: validator failed for field "AppContact.used_for": %w`, err)}
		}
	}
	return nil
}

func (acuo *AppContactUpdateOne) sqlSave(ctx context.Context) (_node *AppContact, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appcontact.Table,
			Columns: appcontact.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appcontact.FieldID,
			},
		},
	}
	id, ok := acuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppContact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := acuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appcontact.FieldID)
		for _, f := range fields {
			if !appcontact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appcontact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := acuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acuo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appcontact.FieldAppID,
		})
	}
	if value, ok := acuo.mutation.UsedFor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldUsedFor,
		})
	}
	if value, ok := acuo.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldSender,
		})
	}
	if value, ok := acuo.mutation.Account(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldAccount,
		})
	}
	if value, ok := acuo.mutation.AccountType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appcontact.FieldAccountType,
		})
	}
	if value, ok := acuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldCreateAt,
		})
	}
	if value, ok := acuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldCreateAt,
		})
	}
	if value, ok := acuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldUpdateAt,
		})
	}
	if value, ok := acuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appcontact.FieldUpdateAt,
		})
	}
	_node = &AppContact{config: acuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, acuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appcontact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
