// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppEmailTemplateQuery is the builder for querying AppEmailTemplate entities.
type AppEmailTemplateQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppEmailTemplate
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppEmailTemplateQuery builder.
func (aetq *AppEmailTemplateQuery) Where(ps ...predicate.AppEmailTemplate) *AppEmailTemplateQuery {
	aetq.predicates = append(aetq.predicates, ps...)
	return aetq
}

// Limit adds a limit step to the query.
func (aetq *AppEmailTemplateQuery) Limit(limit int) *AppEmailTemplateQuery {
	aetq.limit = &limit
	return aetq
}

// Offset adds an offset step to the query.
func (aetq *AppEmailTemplateQuery) Offset(offset int) *AppEmailTemplateQuery {
	aetq.offset = &offset
	return aetq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aetq *AppEmailTemplateQuery) Unique(unique bool) *AppEmailTemplateQuery {
	aetq.unique = &unique
	return aetq
}

// Order adds an order step to the query.
func (aetq *AppEmailTemplateQuery) Order(o ...OrderFunc) *AppEmailTemplateQuery {
	aetq.order = append(aetq.order, o...)
	return aetq
}

// First returns the first AppEmailTemplate entity from the query.
// Returns a *NotFoundError when no AppEmailTemplate was found.
func (aetq *AppEmailTemplateQuery) First(ctx context.Context) (*AppEmailTemplate, error) {
	nodes, err := aetq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appemailtemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) FirstX(ctx context.Context) *AppEmailTemplate {
	node, err := aetq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppEmailTemplate ID from the query.
// Returns a *NotFoundError when no AppEmailTemplate ID was found.
func (aetq *AppEmailTemplateQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aetq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appemailtemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aetq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppEmailTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppEmailTemplate entity is found.
// Returns a *NotFoundError when no AppEmailTemplate entities are found.
func (aetq *AppEmailTemplateQuery) Only(ctx context.Context) (*AppEmailTemplate, error) {
	nodes, err := aetq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appemailtemplate.Label}
	default:
		return nil, &NotSingularError{appemailtemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) OnlyX(ctx context.Context) *AppEmailTemplate {
	node, err := aetq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppEmailTemplate ID in the query.
// Returns a *NotSingularError when more than one AppEmailTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (aetq *AppEmailTemplateQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aetq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = &NotSingularError{appemailtemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aetq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppEmailTemplates.
func (aetq *AppEmailTemplateQuery) All(ctx context.Context) ([]*AppEmailTemplate, error) {
	if err := aetq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aetq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) AllX(ctx context.Context) []*AppEmailTemplate {
	nodes, err := aetq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppEmailTemplate IDs.
func (aetq *AppEmailTemplateQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := aetq.Select(appemailtemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aetq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aetq *AppEmailTemplateQuery) Count(ctx context.Context) (int, error) {
	if err := aetq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aetq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) CountX(ctx context.Context) int {
	count, err := aetq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aetq *AppEmailTemplateQuery) Exist(ctx context.Context) (bool, error) {
	if err := aetq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aetq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aetq *AppEmailTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := aetq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppEmailTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aetq *AppEmailTemplateQuery) Clone() *AppEmailTemplateQuery {
	if aetq == nil {
		return nil
	}
	return &AppEmailTemplateQuery{
		config:     aetq.config,
		limit:      aetq.limit,
		offset:     aetq.offset,
		order:      append([]OrderFunc{}, aetq.order...),
		predicates: append([]predicate.AppEmailTemplate{}, aetq.predicates...),
		// clone intermediate query.
		sql:    aetq.sql.Clone(),
		path:   aetq.path,
		unique: aetq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppEmailTemplate.Query().
//		GroupBy(appemailtemplate.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aetq *AppEmailTemplateQuery) GroupBy(field string, fields ...string) *AppEmailTemplateGroupBy {
	group := &AppEmailTemplateGroupBy{config: aetq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aetq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aetq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppEmailTemplate.Query().
//		Select(appemailtemplate.FieldAppID).
//		Scan(ctx, &v)
//
func (aetq *AppEmailTemplateQuery) Select(fields ...string) *AppEmailTemplateSelect {
	aetq.fields = append(aetq.fields, fields...)
	return &AppEmailTemplateSelect{AppEmailTemplateQuery: aetq}
}

func (aetq *AppEmailTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aetq.fields {
		if !appemailtemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aetq.path != nil {
		prev, err := aetq.path(ctx)
		if err != nil {
			return err
		}
		aetq.sql = prev
	}
	return nil
}

func (aetq *AppEmailTemplateQuery) sqlAll(ctx context.Context) ([]*AppEmailTemplate, error) {
	var (
		nodes = []*AppEmailTemplate{}
		_spec = aetq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppEmailTemplate{config: aetq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, aetq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aetq *AppEmailTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aetq.querySpec()
	_spec.Node.Columns = aetq.fields
	if len(aetq.fields) > 0 {
		_spec.Unique = aetq.unique != nil && *aetq.unique
	}
	return sqlgraph.CountNodes(ctx, aetq.driver, _spec)
}

func (aetq *AppEmailTemplateQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aetq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aetq *AppEmailTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appemailtemplate.FieldID,
			},
		},
		From:   aetq.sql,
		Unique: true,
	}
	if unique := aetq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aetq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appemailtemplate.FieldID)
		for i := range fields {
			if fields[i] != appemailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aetq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aetq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aetq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aetq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aetq *AppEmailTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aetq.driver.Dialect())
	t1 := builder.Table(appemailtemplate.Table)
	columns := aetq.fields
	if len(columns) == 0 {
		columns = appemailtemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aetq.sql != nil {
		selector = aetq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aetq.unique != nil && *aetq.unique {
		selector.Distinct()
	}
	for _, p := range aetq.predicates {
		p(selector)
	}
	for _, p := range aetq.order {
		p(selector)
	}
	if offset := aetq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aetq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppEmailTemplateGroupBy is the group-by builder for AppEmailTemplate entities.
type AppEmailTemplateGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aetgb *AppEmailTemplateGroupBy) Aggregate(fns ...AggregateFunc) *AppEmailTemplateGroupBy {
	aetgb.fns = append(aetgb.fns, fns...)
	return aetgb
}

// Scan applies the group-by query and scans the result into the given value.
func (aetgb *AppEmailTemplateGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aetgb.path(ctx)
	if err != nil {
		return err
	}
	aetgb.sql = query
	return aetgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aetgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aetgb.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aetgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) StringsX(ctx context.Context) []string {
	v, err := aetgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aetgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) StringX(ctx context.Context) string {
	v, err := aetgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aetgb.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aetgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) IntsX(ctx context.Context) []int {
	v, err := aetgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aetgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) IntX(ctx context.Context) int {
	v, err := aetgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aetgb.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aetgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aetgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aetgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aetgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aetgb.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aetgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aetgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aetgb *AppEmailTemplateGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aetgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aetgb *AppEmailTemplateGroupBy) BoolX(ctx context.Context) bool {
	v, err := aetgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aetgb *AppEmailTemplateGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aetgb.fields {
		if !appemailtemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aetgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aetgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aetgb *AppEmailTemplateGroupBy) sqlQuery() *sql.Selector {
	selector := aetgb.sql.Select()
	aggregation := make([]string, 0, len(aetgb.fns))
	for _, fn := range aetgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aetgb.fields)+len(aetgb.fns))
		for _, f := range aetgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aetgb.fields...)...)
}

// AppEmailTemplateSelect is the builder for selecting fields of AppEmailTemplate entities.
type AppEmailTemplateSelect struct {
	*AppEmailTemplateQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aets *AppEmailTemplateSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aets.prepareQuery(ctx); err != nil {
		return err
	}
	aets.sql = aets.AppEmailTemplateQuery.sqlQuery(ctx)
	return aets.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) ScanX(ctx context.Context, v interface{}) {
	if err := aets.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Strings(ctx context.Context) ([]string, error) {
	if len(aets.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aets.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) StringsX(ctx context.Context) []string {
	v, err := aets.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aets.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) StringX(ctx context.Context) string {
	v, err := aets.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Ints(ctx context.Context) ([]int, error) {
	if len(aets.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aets.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) IntsX(ctx context.Context) []int {
	v, err := aets.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aets.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) IntX(ctx context.Context) int {
	v, err := aets.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aets.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aets.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) Float64sX(ctx context.Context) []float64 {
	v, err := aets.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aets.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) Float64X(ctx context.Context) float64 {
	v, err := aets.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aets.fields) > 1 {
		return nil, errors.New("ent: AppEmailTemplateSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aets.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) BoolsX(ctx context.Context) []bool {
	v, err := aets.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aets *AppEmailTemplateSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aets.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appemailtemplate.Label}
	default:
		err = fmt.Errorf("ent: AppEmailTemplateSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aets *AppEmailTemplateSelect) BoolX(ctx context.Context) bool {
	v, err := aets.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aets *AppEmailTemplateSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aets.sql.Query()
	if err := aets.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
