// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
)

// AppEmailTemplate is the model entity for the AppEmailTemplate schema.
type AppEmailTemplate struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppEmailTemplate) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case appemailtemplate.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppEmailTemplate", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppEmailTemplate fields.
func (aet *AppEmailTemplate) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appemailtemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			aet.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this AppEmailTemplate.
// Note that you need to call AppEmailTemplate.Unwrap() before calling this method if this AppEmailTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (aet *AppEmailTemplate) Update() *AppEmailTemplateUpdateOne {
	return (&AppEmailTemplateClient{config: aet.config}).UpdateOne(aet)
}

// Unwrap unwraps the AppEmailTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aet *AppEmailTemplate) Unwrap() *AppEmailTemplate {
	tx, ok := aet.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppEmailTemplate is not a transactional entity")
	}
	aet.config.driver = tx.drv
	return aet
}

// String implements the fmt.Stringer.
func (aet *AppEmailTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("AppEmailTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v", aet.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AppEmailTemplates is a parsable slice of AppEmailTemplate.
type AppEmailTemplates []*AppEmailTemplate

func (aet AppEmailTemplates) config(cfg config) {
	for _i := range aet {
		aet[_i].config = cfg
	}
}
