// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/predicate"
)

// AppEmailTemplateUpdate is the builder for updating AppEmailTemplate entities.
type AppEmailTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *AppEmailTemplateMutation
}

// Where appends a list predicates to the AppEmailTemplateUpdate builder.
func (aetu *AppEmailTemplateUpdate) Where(ps ...predicate.AppEmailTemplate) *AppEmailTemplateUpdate {
	aetu.mutation.Where(ps...)
	return aetu
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetu *AppEmailTemplateUpdate) Mutation() *AppEmailTemplateMutation {
	return aetu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aetu *AppEmailTemplateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aetu.hooks) == 0 {
		affected, err = aetu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aetu.mutation = mutation
			affected, err = aetu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aetu.hooks) - 1; i >= 0; i-- {
			if aetu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := aetu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aetu *AppEmailTemplateUpdate) Exec(ctx context.Context) error {
	_, err := aetu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) ExecX(ctx context.Context) {
	if err := aetu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aetu *AppEmailTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	if ps := aetu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aetu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AppEmailTemplateUpdateOne is the builder for updating a single AppEmailTemplate entity.
type AppEmailTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppEmailTemplateMutation
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetuo *AppEmailTemplateUpdateOne) Mutation() *AppEmailTemplateMutation {
	return aetuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aetuo *AppEmailTemplateUpdateOne) Select(field string, fields ...string) *AppEmailTemplateUpdateOne {
	aetuo.fields = append([]string{field}, fields...)
	return aetuo
}

// Save executes the query and returns the updated AppEmailTemplate entity.
func (aetuo *AppEmailTemplateUpdateOne) Save(ctx context.Context) (*AppEmailTemplate, error) {
	var (
		err  error
		node *AppEmailTemplate
	)
	if len(aetuo.hooks) == 0 {
		node, err = aetuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aetuo.mutation = mutation
			node, err = aetuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aetuo.hooks) - 1; i >= 0; i-- {
			if aetuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) SaveX(ctx context.Context) *AppEmailTemplate {
	node, err := aetuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aetuo *AppEmailTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := aetuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := aetuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aetuo *AppEmailTemplateUpdateOne) sqlSave(ctx context.Context) (_node *AppEmailTemplate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	id, ok := aetuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppEmailTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aetuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appemailtemplate.FieldID)
		for _, f := range fields {
			if !appemailtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appemailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aetuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &AppEmailTemplate{config: aetuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aetuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
