// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppEmailTemplateUpdate is the builder for updating AppEmailTemplate entities.
type AppEmailTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *AppEmailTemplateMutation
}

// Where appends a list predicates to the AppEmailTemplateUpdate builder.
func (aetu *AppEmailTemplateUpdate) Where(ps ...predicate.AppEmailTemplate) *AppEmailTemplateUpdate {
	aetu.mutation.Where(ps...)
	return aetu
}

// SetAppID sets the "app_id" field.
func (aetu *AppEmailTemplateUpdate) SetAppID(u uuid.UUID) *AppEmailTemplateUpdate {
	aetu.mutation.SetAppID(u)
	return aetu
}

// SetLangID sets the "lang_id" field.
func (aetu *AppEmailTemplateUpdate) SetLangID(u uuid.UUID) *AppEmailTemplateUpdate {
	aetu.mutation.SetLangID(u)
	return aetu
}

// SetSender sets the "sender" field.
func (aetu *AppEmailTemplateUpdate) SetSender(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetSender(s)
	return aetu
}

// SetReplyTo sets the "reply_to" field.
func (aetu *AppEmailTemplateUpdate) SetReplyTo(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetReplyTo(s)
	return aetu
}

// SetCcTo sets the "cc_to" field.
func (aetu *AppEmailTemplateUpdate) SetCcTo(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetCcTo(s)
	return aetu
}

// SetSubject sets the "subject" field.
func (aetu *AppEmailTemplateUpdate) SetSubject(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetSubject(s)
	return aetu
}

// SetBody sets the "body" field.
func (aetu *AppEmailTemplateUpdate) SetBody(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetBody(s)
	return aetu
}

// SetCreateAt sets the "create_at" field.
func (aetu *AppEmailTemplateUpdate) SetCreateAt(u uint32) *AppEmailTemplateUpdate {
	aetu.mutation.ResetCreateAt()
	aetu.mutation.SetCreateAt(u)
	return aetu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (aetu *AppEmailTemplateUpdate) SetNillableCreateAt(u *uint32) *AppEmailTemplateUpdate {
	if u != nil {
		aetu.SetCreateAt(*u)
	}
	return aetu
}

// AddCreateAt adds u to the "create_at" field.
func (aetu *AppEmailTemplateUpdate) AddCreateAt(u int32) *AppEmailTemplateUpdate {
	aetu.mutation.AddCreateAt(u)
	return aetu
}

// SetUpdateAt sets the "update_at" field.
func (aetu *AppEmailTemplateUpdate) SetUpdateAt(u uint32) *AppEmailTemplateUpdate {
	aetu.mutation.ResetUpdateAt()
	aetu.mutation.SetUpdateAt(u)
	return aetu
}

// AddUpdateAt adds u to the "update_at" field.
func (aetu *AppEmailTemplateUpdate) AddUpdateAt(u int32) *AppEmailTemplateUpdate {
	aetu.mutation.AddUpdateAt(u)
	return aetu
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetu *AppEmailTemplateUpdate) Mutation() *AppEmailTemplateMutation {
	return aetu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aetu *AppEmailTemplateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	aetu.defaults()
	if len(aetu.hooks) == 0 {
		affected, err = aetu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aetu.mutation = mutation
			affected, err = aetu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aetu.hooks) - 1; i >= 0; i-- {
			if aetu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := aetu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aetu *AppEmailTemplateUpdate) Exec(ctx context.Context) error {
	_, err := aetu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) ExecX(ctx context.Context) {
	if err := aetu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aetu *AppEmailTemplateUpdate) defaults() {
	if _, ok := aetu.mutation.UpdateAt(); !ok {
		v := appemailtemplate.UpdateDefaultUpdateAt()
		aetu.mutation.SetUpdateAt(v)
	}
}

func (aetu *AppEmailTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	if ps := aetu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aetu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldAppID,
		})
	}
	if value, ok := aetu.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldLangID,
		})
	}
	if value, ok := aetu.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSender,
		})
	}
	if value, ok := aetu.mutation.ReplyTo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldReplyTo,
		})
	}
	if value, ok := aetu.mutation.CcTo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldCcTo,
		})
	}
	if value, ok := aetu.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSubject,
		})
	}
	if value, ok := aetu.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldBody,
		})
	}
	if value, ok := aetu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreateAt,
		})
	}
	if value, ok := aetu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreateAt,
		})
	}
	if value, ok := aetu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdateAt,
		})
	}
	if value, ok := aetu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aetu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AppEmailTemplateUpdateOne is the builder for updating a single AppEmailTemplate entity.
type AppEmailTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppEmailTemplateMutation
}

// SetAppID sets the "app_id" field.
func (aetuo *AppEmailTemplateUpdateOne) SetAppID(u uuid.UUID) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetAppID(u)
	return aetuo
}

// SetLangID sets the "lang_id" field.
func (aetuo *AppEmailTemplateUpdateOne) SetLangID(u uuid.UUID) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetLangID(u)
	return aetuo
}

// SetSender sets the "sender" field.
func (aetuo *AppEmailTemplateUpdateOne) SetSender(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetSender(s)
	return aetuo
}

// SetReplyTo sets the "reply_to" field.
func (aetuo *AppEmailTemplateUpdateOne) SetReplyTo(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetReplyTo(s)
	return aetuo
}

// SetCcTo sets the "cc_to" field.
func (aetuo *AppEmailTemplateUpdateOne) SetCcTo(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetCcTo(s)
	return aetuo
}

// SetSubject sets the "subject" field.
func (aetuo *AppEmailTemplateUpdateOne) SetSubject(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetSubject(s)
	return aetuo
}

// SetBody sets the "body" field.
func (aetuo *AppEmailTemplateUpdateOne) SetBody(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetBody(s)
	return aetuo
}

// SetCreateAt sets the "create_at" field.
func (aetuo *AppEmailTemplateUpdateOne) SetCreateAt(u uint32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.ResetCreateAt()
	aetuo.mutation.SetCreateAt(u)
	return aetuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (aetuo *AppEmailTemplateUpdateOne) SetNillableCreateAt(u *uint32) *AppEmailTemplateUpdateOne {
	if u != nil {
		aetuo.SetCreateAt(*u)
	}
	return aetuo
}

// AddCreateAt adds u to the "create_at" field.
func (aetuo *AppEmailTemplateUpdateOne) AddCreateAt(u int32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.AddCreateAt(u)
	return aetuo
}

// SetUpdateAt sets the "update_at" field.
func (aetuo *AppEmailTemplateUpdateOne) SetUpdateAt(u uint32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.ResetUpdateAt()
	aetuo.mutation.SetUpdateAt(u)
	return aetuo
}

// AddUpdateAt adds u to the "update_at" field.
func (aetuo *AppEmailTemplateUpdateOne) AddUpdateAt(u int32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.AddUpdateAt(u)
	return aetuo
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetuo *AppEmailTemplateUpdateOne) Mutation() *AppEmailTemplateMutation {
	return aetuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aetuo *AppEmailTemplateUpdateOne) Select(field string, fields ...string) *AppEmailTemplateUpdateOne {
	aetuo.fields = append([]string{field}, fields...)
	return aetuo
}

// Save executes the query and returns the updated AppEmailTemplate entity.
func (aetuo *AppEmailTemplateUpdateOne) Save(ctx context.Context) (*AppEmailTemplate, error) {
	var (
		err  error
		node *AppEmailTemplate
	)
	aetuo.defaults()
	if len(aetuo.hooks) == 0 {
		node, err = aetuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aetuo.mutation = mutation
			node, err = aetuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aetuo.hooks) - 1; i >= 0; i-- {
			if aetuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) SaveX(ctx context.Context) *AppEmailTemplate {
	node, err := aetuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aetuo *AppEmailTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := aetuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := aetuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aetuo *AppEmailTemplateUpdateOne) defaults() {
	if _, ok := aetuo.mutation.UpdateAt(); !ok {
		v := appemailtemplate.UpdateDefaultUpdateAt()
		aetuo.mutation.SetUpdateAt(v)
	}
}

func (aetuo *AppEmailTemplateUpdateOne) sqlSave(ctx context.Context) (_node *AppEmailTemplate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	id, ok := aetuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppEmailTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aetuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appemailtemplate.FieldID)
		for _, f := range fields {
			if !appemailtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appemailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aetuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aetuo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldAppID,
		})
	}
	if value, ok := aetuo.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldLangID,
		})
	}
	if value, ok := aetuo.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSender,
		})
	}
	if value, ok := aetuo.mutation.ReplyTo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldReplyTo,
		})
	}
	if value, ok := aetuo.mutation.CcTo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldCcTo,
		})
	}
	if value, ok := aetuo.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSubject,
		})
	}
	if value, ok := aetuo.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldBody,
		})
	}
	if value, ok := aetuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreateAt,
		})
	}
	if value, ok := aetuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreateAt,
		})
	}
	if value, ok := aetuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdateAt,
		})
	}
	if value, ok := aetuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdateAt,
		})
	}
	_node = &AppEmailTemplate{config: aetuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aetuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
