// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
)

// AppEmailTemplateCreate is the builder for creating a AppEmailTemplate entity.
type AppEmailTemplateCreate struct {
	config
	mutation *AppEmailTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetc *AppEmailTemplateCreate) Mutation() *AppEmailTemplateMutation {
	return aetc.mutation
}

// Save creates the AppEmailTemplate in the database.
func (aetc *AppEmailTemplateCreate) Save(ctx context.Context) (*AppEmailTemplate, error) {
	var (
		err  error
		node *AppEmailTemplate
	)
	if len(aetc.hooks) == 0 {
		if err = aetc.check(); err != nil {
			return nil, err
		}
		node, err = aetc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aetc.check(); err != nil {
				return nil, err
			}
			aetc.mutation = mutation
			if node, err = aetc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aetc.hooks) - 1; i >= 0; i-- {
			if aetc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aetc *AppEmailTemplateCreate) SaveX(ctx context.Context) *AppEmailTemplate {
	v, err := aetc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aetc *AppEmailTemplateCreate) Exec(ctx context.Context) error {
	_, err := aetc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetc *AppEmailTemplateCreate) ExecX(ctx context.Context) {
	if err := aetc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aetc *AppEmailTemplateCreate) check() error {
	return nil
}

func (aetc *AppEmailTemplateCreate) sqlSave(ctx context.Context) (*AppEmailTemplate, error) {
	_node, _spec := aetc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aetc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aetc *AppEmailTemplateCreate) createSpec() (*AppEmailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &AppEmailTemplate{config: aetc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: appemailtemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appemailtemplate.FieldID,
			},
		}
	)
	_spec.OnConflict = aetc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (aetc *AppEmailTemplateCreate) OnConflict(opts ...sql.ConflictOption) *AppEmailTemplateUpsertOne {
	aetc.conflict = opts
	return &AppEmailTemplateUpsertOne{
		create: aetc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (aetc *AppEmailTemplateCreate) OnConflictColumns(columns ...string) *AppEmailTemplateUpsertOne {
	aetc.conflict = append(aetc.conflict, sql.ConflictColumns(columns...))
	return &AppEmailTemplateUpsertOne{
		create: aetc,
	}
}

type (
	// AppEmailTemplateUpsertOne is the builder for "upsert"-ing
	//  one AppEmailTemplate node.
	AppEmailTemplateUpsertOne struct {
		create *AppEmailTemplateCreate
	}

	// AppEmailTemplateUpsert is the "OnConflict" setter.
	AppEmailTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppEmailTemplateUpsertOne) UpdateNewValues() *AppEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.AppEmailTemplate.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *AppEmailTemplateUpsertOne) Ignore() *AppEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppEmailTemplateUpsertOne) DoNothing() *AppEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppEmailTemplateCreate.OnConflict
// documentation for more info.
func (u *AppEmailTemplateUpsertOne) Update(set func(*AppEmailTemplateUpsert)) *AppEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppEmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppEmailTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppEmailTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppEmailTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppEmailTemplateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppEmailTemplateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppEmailTemplateCreateBulk is the builder for creating many AppEmailTemplate entities in bulk.
type AppEmailTemplateCreateBulk struct {
	config
	builders []*AppEmailTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the AppEmailTemplate entities in the database.
func (aetcb *AppEmailTemplateCreateBulk) Save(ctx context.Context) ([]*AppEmailTemplate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aetcb.builders))
	nodes := make([]*AppEmailTemplate, len(aetcb.builders))
	mutators := make([]Mutator, len(aetcb.builders))
	for i := range aetcb.builders {
		func(i int, root context.Context) {
			builder := aetcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppEmailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aetcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = aetcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aetcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aetcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aetcb *AppEmailTemplateCreateBulk) SaveX(ctx context.Context) []*AppEmailTemplate {
	v, err := aetcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aetcb *AppEmailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := aetcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetcb *AppEmailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := aetcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppEmailTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (aetcb *AppEmailTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppEmailTemplateUpsertBulk {
	aetcb.conflict = opts
	return &AppEmailTemplateUpsertBulk{
		create: aetcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (aetcb *AppEmailTemplateCreateBulk) OnConflictColumns(columns ...string) *AppEmailTemplateUpsertBulk {
	aetcb.conflict = append(aetcb.conflict, sql.ConflictColumns(columns...))
	return &AppEmailTemplateUpsertBulk{
		create: aetcb,
	}
}

// AppEmailTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of AppEmailTemplate nodes.
type AppEmailTemplateUpsertBulk struct {
	create *AppEmailTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppEmailTemplateUpsertBulk) UpdateNewValues() *AppEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppEmailTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *AppEmailTemplateUpsertBulk) Ignore() *AppEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppEmailTemplateUpsertBulk) DoNothing() *AppEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppEmailTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *AppEmailTemplateUpsertBulk) Update(set func(*AppEmailTemplateUpsert)) *AppEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppEmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppEmailTemplateUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppEmailTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppEmailTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppEmailTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
