// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appuseremailtemplate"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/predicate"
)

// AppUserEmailTemplateUpdate is the builder for updating AppUserEmailTemplate entities.
type AppUserEmailTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *AppUserEmailTemplateMutation
}

// Where appends a list predicates to the AppUserEmailTemplateUpdate builder.
func (auetu *AppUserEmailTemplateUpdate) Where(ps ...predicate.AppUserEmailTemplate) *AppUserEmailTemplateUpdate {
	auetu.mutation.Where(ps...)
	return auetu
}

// Mutation returns the AppUserEmailTemplateMutation object of the builder.
func (auetu *AppUserEmailTemplateUpdate) Mutation() *AppUserEmailTemplateMutation {
	return auetu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (auetu *AppUserEmailTemplateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(auetu.hooks) == 0 {
		affected, err = auetu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppUserEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auetu.mutation = mutation
			affected, err = auetu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(auetu.hooks) - 1; i >= 0; i-- {
			if auetu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auetu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auetu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (auetu *AppUserEmailTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := auetu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (auetu *AppUserEmailTemplateUpdate) Exec(ctx context.Context) error {
	_, err := auetu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auetu *AppUserEmailTemplateUpdate) ExecX(ctx context.Context) {
	if err := auetu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auetu *AppUserEmailTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appuseremailtemplate.Table,
			Columns: appuseremailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appuseremailtemplate.FieldID,
			},
		},
	}
	if ps := auetu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, auetu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appuseremailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AppUserEmailTemplateUpdateOne is the builder for updating a single AppUserEmailTemplate entity.
type AppUserEmailTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppUserEmailTemplateMutation
}

// Mutation returns the AppUserEmailTemplateMutation object of the builder.
func (auetuo *AppUserEmailTemplateUpdateOne) Mutation() *AppUserEmailTemplateMutation {
	return auetuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auetuo *AppUserEmailTemplateUpdateOne) Select(field string, fields ...string) *AppUserEmailTemplateUpdateOne {
	auetuo.fields = append([]string{field}, fields...)
	return auetuo
}

// Save executes the query and returns the updated AppUserEmailTemplate entity.
func (auetuo *AppUserEmailTemplateUpdateOne) Save(ctx context.Context) (*AppUserEmailTemplate, error) {
	var (
		err  error
		node *AppUserEmailTemplate
	)
	if len(auetuo.hooks) == 0 {
		node, err = auetuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppUserEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auetuo.mutation = mutation
			node, err = auetuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auetuo.hooks) - 1; i >= 0; i-- {
			if auetuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auetuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auetuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auetuo *AppUserEmailTemplateUpdateOne) SaveX(ctx context.Context) *AppUserEmailTemplate {
	node, err := auetuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auetuo *AppUserEmailTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := auetuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auetuo *AppUserEmailTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := auetuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auetuo *AppUserEmailTemplateUpdateOne) sqlSave(ctx context.Context) (_node *AppUserEmailTemplate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appuseremailtemplate.Table,
			Columns: appuseremailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appuseremailtemplate.FieldID,
			},
		},
	}
	id, ok := auetuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppUserEmailTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auetuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appuseremailtemplate.FieldID)
		for _, f := range fields {
			if !appuseremailtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appuseremailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auetuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &AppUserEmailTemplate{config: auetuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auetuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appuseremailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
