// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appuseremailtemplate"
)

// AppUserEmailTemplate is the model entity for the AppUserEmailTemplate schema.
type AppUserEmailTemplate struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppUserEmailTemplate) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case appuseremailtemplate.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppUserEmailTemplate", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppUserEmailTemplate fields.
func (auet *AppUserEmailTemplate) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appuseremailtemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			auet.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this AppUserEmailTemplate.
// Note that you need to call AppUserEmailTemplate.Unwrap() before calling this method if this AppUserEmailTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (auet *AppUserEmailTemplate) Update() *AppUserEmailTemplateUpdateOne {
	return (&AppUserEmailTemplateClient{config: auet.config}).UpdateOne(auet)
}

// Unwrap unwraps the AppUserEmailTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (auet *AppUserEmailTemplate) Unwrap() *AppUserEmailTemplate {
	tx, ok := auet.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppUserEmailTemplate is not a transactional entity")
	}
	auet.config.driver = tx.drv
	return auet
}

// String implements the fmt.Stringer.
func (auet *AppUserEmailTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("AppUserEmailTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v", auet.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AppUserEmailTemplates is a parsable slice of AppUserEmailTemplate.
type AppUserEmailTemplates []*AppUserEmailTemplate

func (auet AppUserEmailTemplates) config(cfg config) {
	for _i := range auet {
		auet[_i].config = cfg
	}
}
