// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appuseremailtemplate"
)

// AppUserEmailTemplateCreate is the builder for creating a AppUserEmailTemplate entity.
type AppUserEmailTemplateCreate struct {
	config
	mutation *AppUserEmailTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the AppUserEmailTemplateMutation object of the builder.
func (auetc *AppUserEmailTemplateCreate) Mutation() *AppUserEmailTemplateMutation {
	return auetc.mutation
}

// Save creates the AppUserEmailTemplate in the database.
func (auetc *AppUserEmailTemplateCreate) Save(ctx context.Context) (*AppUserEmailTemplate, error) {
	var (
		err  error
		node *AppUserEmailTemplate
	)
	if len(auetc.hooks) == 0 {
		if err = auetc.check(); err != nil {
			return nil, err
		}
		node, err = auetc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppUserEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auetc.check(); err != nil {
				return nil, err
			}
			auetc.mutation = mutation
			if node, err = auetc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(auetc.hooks) - 1; i >= 0; i-- {
			if auetc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auetc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auetc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (auetc *AppUserEmailTemplateCreate) SaveX(ctx context.Context) *AppUserEmailTemplate {
	v, err := auetc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (auetc *AppUserEmailTemplateCreate) Exec(ctx context.Context) error {
	_, err := auetc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auetc *AppUserEmailTemplateCreate) ExecX(ctx context.Context) {
	if err := auetc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auetc *AppUserEmailTemplateCreate) check() error {
	return nil
}

func (auetc *AppUserEmailTemplateCreate) sqlSave(ctx context.Context) (*AppUserEmailTemplate, error) {
	_node, _spec := auetc.createSpec()
	if err := sqlgraph.CreateNode(ctx, auetc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (auetc *AppUserEmailTemplateCreate) createSpec() (*AppUserEmailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &AppUserEmailTemplate{config: auetc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: appuseremailtemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appuseremailtemplate.FieldID,
			},
		}
	)
	_spec.OnConflict = auetc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (auetc *AppUserEmailTemplateCreate) OnConflict(opts ...sql.ConflictOption) *AppUserEmailTemplateUpsertOne {
	auetc.conflict = opts
	return &AppUserEmailTemplateUpsertOne{
		create: auetc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (auetc *AppUserEmailTemplateCreate) OnConflictColumns(columns ...string) *AppUserEmailTemplateUpsertOne {
	auetc.conflict = append(auetc.conflict, sql.ConflictColumns(columns...))
	return &AppUserEmailTemplateUpsertOne{
		create: auetc,
	}
}

type (
	// AppUserEmailTemplateUpsertOne is the builder for "upsert"-ing
	//  one AppUserEmailTemplate node.
	AppUserEmailTemplateUpsertOne struct {
		create *AppUserEmailTemplateCreate
	}

	// AppUserEmailTemplateUpsert is the "OnConflict" setter.
	AppUserEmailTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppUserEmailTemplateUpsertOne) UpdateNewValues() *AppUserEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.AppUserEmailTemplate.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *AppUserEmailTemplateUpsertOne) Ignore() *AppUserEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppUserEmailTemplateUpsertOne) DoNothing() *AppUserEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppUserEmailTemplateCreate.OnConflict
// documentation for more info.
func (u *AppUserEmailTemplateUpsertOne) Update(set func(*AppUserEmailTemplateUpsert)) *AppUserEmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppUserEmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppUserEmailTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppUserEmailTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppUserEmailTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppUserEmailTemplateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppUserEmailTemplateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppUserEmailTemplateCreateBulk is the builder for creating many AppUserEmailTemplate entities in bulk.
type AppUserEmailTemplateCreateBulk struct {
	config
	builders []*AppUserEmailTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the AppUserEmailTemplate entities in the database.
func (auetcb *AppUserEmailTemplateCreateBulk) Save(ctx context.Context) ([]*AppUserEmailTemplate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(auetcb.builders))
	nodes := make([]*AppUserEmailTemplate, len(auetcb.builders))
	mutators := make([]Mutator, len(auetcb.builders))
	for i := range auetcb.builders {
		func(i int, root context.Context) {
			builder := auetcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppUserEmailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, auetcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = auetcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, auetcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, auetcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (auetcb *AppUserEmailTemplateCreateBulk) SaveX(ctx context.Context) []*AppUserEmailTemplate {
	v, err := auetcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (auetcb *AppUserEmailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := auetcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auetcb *AppUserEmailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := auetcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppUserEmailTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (auetcb *AppUserEmailTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppUserEmailTemplateUpsertBulk {
	auetcb.conflict = opts
	return &AppUserEmailTemplateUpsertBulk{
		create: auetcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (auetcb *AppUserEmailTemplateCreateBulk) OnConflictColumns(columns ...string) *AppUserEmailTemplateUpsertBulk {
	auetcb.conflict = append(auetcb.conflict, sql.ConflictColumns(columns...))
	return &AppUserEmailTemplateUpsertBulk{
		create: auetcb,
	}
}

// AppUserEmailTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of AppUserEmailTemplate nodes.
type AppUserEmailTemplateUpsertBulk struct {
	create *AppUserEmailTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppUserEmailTemplateUpsertBulk) UpdateNewValues() *AppUserEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppUserEmailTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *AppUserEmailTemplateUpsertBulk) Ignore() *AppUserEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppUserEmailTemplateUpsertBulk) DoNothing() *AppUserEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppUserEmailTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *AppUserEmailTemplateUpsertBulk) Update(set func(*AppUserEmailTemplateUpsert)) *AppUserEmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppUserEmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppUserEmailTemplateUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppUserEmailTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppUserEmailTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppUserEmailTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
