// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-gateway/pkg/db/ent/appuseremailtemplate"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppEmailTemplate is the client for interacting with the AppEmailTemplate builders.
	AppEmailTemplate *AppEmailTemplateClient
	// AppUserEmailTemplate is the client for interacting with the AppUserEmailTemplate builders.
	AppUserEmailTemplate *AppUserEmailTemplateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppEmailTemplate = NewAppEmailTemplateClient(c.config)
	c.AppUserEmailTemplate = NewAppUserEmailTemplateClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		AppEmailTemplate:     NewAppEmailTemplateClient(cfg),
		AppUserEmailTemplate: NewAppUserEmailTemplateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		AppEmailTemplate:     NewAppEmailTemplateClient(cfg),
		AppUserEmailTemplate: NewAppUserEmailTemplateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppEmailTemplate.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AppEmailTemplate.Use(hooks...)
	c.AppUserEmailTemplate.Use(hooks...)
}

// AppEmailTemplateClient is a client for the AppEmailTemplate schema.
type AppEmailTemplateClient struct {
	config
}

// NewAppEmailTemplateClient returns a client for the AppEmailTemplate from the given config.
func NewAppEmailTemplateClient(c config) *AppEmailTemplateClient {
	return &AppEmailTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appemailtemplate.Hooks(f(g(h())))`.
func (c *AppEmailTemplateClient) Use(hooks ...Hook) {
	c.hooks.AppEmailTemplate = append(c.hooks.AppEmailTemplate, hooks...)
}

// Create returns a create builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Create() *AppEmailTemplateCreate {
	mutation := newAppEmailTemplateMutation(c.config, OpCreate)
	return &AppEmailTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppEmailTemplate entities.
func (c *AppEmailTemplateClient) CreateBulk(builders ...*AppEmailTemplateCreate) *AppEmailTemplateCreateBulk {
	return &AppEmailTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Update() *AppEmailTemplateUpdate {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdate)
	return &AppEmailTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppEmailTemplateClient) UpdateOne(aet *AppEmailTemplate) *AppEmailTemplateUpdateOne {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdateOne, withAppEmailTemplate(aet))
	return &AppEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppEmailTemplateClient) UpdateOneID(id uuid.UUID) *AppEmailTemplateUpdateOne {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdateOne, withAppEmailTemplateID(id))
	return &AppEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Delete() *AppEmailTemplateDelete {
	mutation := newAppEmailTemplateMutation(c.config, OpDelete)
	return &AppEmailTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AppEmailTemplateClient) DeleteOne(aet *AppEmailTemplate) *AppEmailTemplateDeleteOne {
	return c.DeleteOneID(aet.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AppEmailTemplateClient) DeleteOneID(id uuid.UUID) *AppEmailTemplateDeleteOne {
	builder := c.Delete().Where(appemailtemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppEmailTemplateDeleteOne{builder}
}

// Query returns a query builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Query() *AppEmailTemplateQuery {
	return &AppEmailTemplateQuery{
		config: c.config,
	}
}

// Get returns a AppEmailTemplate entity by its id.
func (c *AppEmailTemplateClient) Get(ctx context.Context, id uuid.UUID) (*AppEmailTemplate, error) {
	return c.Query().Where(appemailtemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppEmailTemplateClient) GetX(ctx context.Context, id uuid.UUID) *AppEmailTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppEmailTemplateClient) Hooks() []Hook {
	return c.hooks.AppEmailTemplate
}

// AppUserEmailTemplateClient is a client for the AppUserEmailTemplate schema.
type AppUserEmailTemplateClient struct {
	config
}

// NewAppUserEmailTemplateClient returns a client for the AppUserEmailTemplate from the given config.
func NewAppUserEmailTemplateClient(c config) *AppUserEmailTemplateClient {
	return &AppUserEmailTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appuseremailtemplate.Hooks(f(g(h())))`.
func (c *AppUserEmailTemplateClient) Use(hooks ...Hook) {
	c.hooks.AppUserEmailTemplate = append(c.hooks.AppUserEmailTemplate, hooks...)
}

// Create returns a create builder for AppUserEmailTemplate.
func (c *AppUserEmailTemplateClient) Create() *AppUserEmailTemplateCreate {
	mutation := newAppUserEmailTemplateMutation(c.config, OpCreate)
	return &AppUserEmailTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppUserEmailTemplate entities.
func (c *AppUserEmailTemplateClient) CreateBulk(builders ...*AppUserEmailTemplateCreate) *AppUserEmailTemplateCreateBulk {
	return &AppUserEmailTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppUserEmailTemplate.
func (c *AppUserEmailTemplateClient) Update() *AppUserEmailTemplateUpdate {
	mutation := newAppUserEmailTemplateMutation(c.config, OpUpdate)
	return &AppUserEmailTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppUserEmailTemplateClient) UpdateOne(auet *AppUserEmailTemplate) *AppUserEmailTemplateUpdateOne {
	mutation := newAppUserEmailTemplateMutation(c.config, OpUpdateOne, withAppUserEmailTemplate(auet))
	return &AppUserEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppUserEmailTemplateClient) UpdateOneID(id uuid.UUID) *AppUserEmailTemplateUpdateOne {
	mutation := newAppUserEmailTemplateMutation(c.config, OpUpdateOne, withAppUserEmailTemplateID(id))
	return &AppUserEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppUserEmailTemplate.
func (c *AppUserEmailTemplateClient) Delete() *AppUserEmailTemplateDelete {
	mutation := newAppUserEmailTemplateMutation(c.config, OpDelete)
	return &AppUserEmailTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AppUserEmailTemplateClient) DeleteOne(auet *AppUserEmailTemplate) *AppUserEmailTemplateDeleteOne {
	return c.DeleteOneID(auet.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AppUserEmailTemplateClient) DeleteOneID(id uuid.UUID) *AppUserEmailTemplateDeleteOne {
	builder := c.Delete().Where(appuseremailtemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppUserEmailTemplateDeleteOne{builder}
}

// Query returns a query builder for AppUserEmailTemplate.
func (c *AppUserEmailTemplateClient) Query() *AppUserEmailTemplateQuery {
	return &AppUserEmailTemplateQuery{
		config: c.config,
	}
}

// Get returns a AppUserEmailTemplate entity by its id.
func (c *AppUserEmailTemplateClient) Get(ctx context.Context, id uuid.UUID) (*AppUserEmailTemplate, error) {
	return c.Query().Where(appuseremailtemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppUserEmailTemplateClient) GetX(ctx context.Context, id uuid.UUID) *AppUserEmailTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppUserEmailTemplateClient) Hooks() []Hook {
	return c.hooks.AppUserEmailTemplate
}
