// Code generated by entc, DO NOT EDIT.

package appcontact

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the appcontact type in the database.
	Label = "app_contact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldUsedFor holds the string denoting the used_for field in the database.
	FieldUsedFor = "used_for"
	// FieldSender holds the string denoting the sender field in the database.
	FieldSender = "sender"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// Table holds the table name of the appcontact in the database.
	Table = "app_contacts"
)

// Columns holds all SQL columns for appcontact fields.
var Columns = []string{
	FieldID,
	FieldAppID,
	FieldUsedFor,
	FieldSender,
	FieldAccount,
	FieldAccountType,
	FieldCreateAt,
	FieldUpdateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsedForValidator is a validator for the "used_for" field. It is called by the builders before save.
	UsedForValidator func(string) error
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
