// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppEmailTemplate is the predicate function for appemailtemplate builders.
type AppEmailTemplate func(*sql.Selector)

// AppSMSTemplate is the predicate function for appsmstemplate builders.
type AppSMSTemplate func(*sql.Selector)
